name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: "I'd like the scanner to..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature needed? What problem does it solve?
      placeholder: "When developing X, I often need to..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example
      description: Show how the feature would work (API, CLI, config, etc.)
      render: shell

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New security rule
        - New MCP tool
        - CLI improvement
        - False positive reduction
        - Performance
        - Configuration
        - CI/CD integration
        - Documentation
        - Other
